ui_text = {
    "en": {
        # ========================
        #   LOADING FRAME
        # ========================
        "loading_title": "Initializing aplicação",
        "loading_cards": "Loading cards...",
        "loading_tip": "Please wait a few minutes...",
        "loading_error": "Error loading database!",
        # ===============================
        #  CHANGING LANGUAGE DIALOG
        # ===============================
        "changing_language_title": "Changing Language",
        "changing_language": "Changing language, please wait",
        "error": "Error",
        "language_change_failed": "There was an error changing language",
        # ================================
        #   HEADER
        # ================================
        "read_docs": "Card Consistency File",
        "language": "Language",
        # ================================
        #   HOME FRAME
        # ================================
        "home_title": "Welcome to the Yu-Gi-Oh! Desktop Companion App",
        "home_subtitle": "Browse cards, inspect duelists and their decks and build your own.",
        "check_cards": "Check available cards",
        "duelists": "View duelists",
        "custom_decks": "View custom decks",
        "cards_total": "Cards total",
        "duelists_total": "Duelists total",
        "user_decks_total": "User decks total",
        "dataset_version": "Dataset Version",
        "dataset_version_unknown": "Dataset version: Unknown",
        "last_update": "Last updated",
        "show_new_cards": "Show new cards",
        "no_new_cards_added": "No new cards were added",
        "no_new_cards": "There aren't any new cards available",
        # ================================
        #  CARDS FRAME
        # ================================
        "search_card": "Card search",
        # ================================
        #  DUELISTS FRAME
        # ================================
        "select_duelist": "Select a duelist",
        "filter_all": "All duelists",
        "duel_monsters_anime": "Duel Monsters",
        "duel_spirits": "Duel Spirits",
        "gx": "GX",
        "filter_by": "Filter by",
        "search_duelist": "Search duelist",
        "search_duel_spirit": "Search Duel Spirit",
        "select_duel_spirit": "Select Duel Spirit",
        # ================================
        #  DUELISTS DETAILS FRAME
        # ================================
        "complete_deck": "Complete Deck",
        "incomplete_deck": "Incomplete Deck",
        "duelist_decks": "{name} decks",
        "show_exclusive_cards": "Show exclusive cards",
        "no_decks_found": "No decks found",
        "export_deck": "Export Deck(s)",
        "deck_exporter": "Deck Exporter",
        "deck_export_success": "Deck exported successfully!",
        "decks_export_success": "Decks exported successfully!",
        "deck_import_success": "Deck imported successfully!",
        "decks_import_success": "Decks imported successfully!",
        "deck_export_fail": "Error! Deck export failed.",
        "no_decks_exported": "No decks were exported",
        "generate_deck": "Generate deck",
        "not_enough_cards": "Not enough cards to generate a deck.",
        "deck_generator": "Deck generator",
        "generated_deck": "Generated deck",
        "generate_another_deck": "Generate another deck",
        "text_view": "Text",
        "gallery_view": "Gallery",
        "loading": "Loading...",
        "deck": "Deck",
        "export_individual_deck": "Export deck",
        # ================================
        #  CUSTOM DECKS FRAME
        # ================================
        "import_deck": "Import deck(s)",
        "deck_importer": "Deck importer",
        "could_not_read_deck_file": "Error! Could not read deck file",
        "invalid_card_entry": "Error! Invalid card Format",
        "could_not_import_card": "Error importing card from this deck",
        "deck_imported_successfully": "Deck imported successfully!",
        "deck_import_failed": "Error importing deck!",
        "deck_name": "Deck name",
        "total_cards": "Main / Extra deck",
        "used": "Used",
        "new_deck": "Create new Deck",
        "edit": "Edit deck",
        "toggle_used": "Toggle used",
        "delete": "Delete deck",
        "add_to_deck": "Add to deck",
        "remove_one": "Remove one copy",
        "remove_card": "Remove cards",
        "yes": "Yes",
        "no": "No",
        "editing_deck": "Now editing",
        "deck_cards": "Deck cards",
        "enter_deck_name": "Enter deck name",
        "enter_imported_deck_name": "Enter imported deck name",
        "delete_deck": "Delete deck(s)",
        "deck_remover": "Deck remover",
        "confirm_delete_deck": "Are you sure you want to delete this deck?",
        "confirm_delete_decks": "Are you sure you want to delete these decks?",
        "deck_name_already_exists": "There is already a deck with this name.",
        "deck_deleted_successfully": "Deck(s) deleted successfully!",
        "no_decks_deleted": "No deck to delete",
        "rename_deck": "Rename deck",
        "no_decks_to_export": "Please select a deck to export",
        "deck_not_found": "deck not found",
        "search_decks": "Search decks",
        "invalid_deck_file": "Invalid deck File",
        "limit_reached": "Limit reached",
        "card_limit_reached": "Unable to add more cards. Limit of 3 reached.",
        "deck_notes": "Deck notes",
        "unsaved_changes": "Confirm changes",
        "save_before_closing": "File has been changed. Do you wish to save?",
        "confirm_operation": "Confirm operation",
        "confirm_mark_deck_as_used": 'Do you want to mark the deck "{deck_name}" as used?',
        "confirm_mark_deck_as_unused": 'Do you want to mark the deck "{deck_name}" as not used?',
        # ================================
        #  UI
        # ================================
        "return": "Return",
        "card_details": "Show card details",
        "select_card": "Select a card",
        "spell_card": "Spell card",
        "trap_card": "Trap card",
        "main_deck": "Main deck",
        "extra_deck": "Extra deck",
        "monsters": "Monster cards",
        "spells": "Spell cards",
        "traps": "Trap cards",
        "exclusive_cards": "Exclusive cards",
        "other_cards": "Other cards",
        "new_cards_added": "New cards added",
        "cards_added": "Card(s) added",
        "click_for_more_details": "Click on a card for more details",
        "update_available_title": "New update available!",
        "update_available_message": "There is a new update available. Do you wish to install it?",
        "no_changelog_available": "No changelog available",
        "download_update": "Download update",
        "open_in_browser": "Open in browser",
        "download_complete": "Download complete!",
        "downloading_update": "Downloading update",
        "update_downloaded": "Update downloaded! Wait a few seconds for the app to restart",
        "update_fail": "Error downloading update",
        "ignore": "Ignore",
        "updater_not_found": "Error! Updater not found",
        "cards": "cards",
        "loading_database": "Loading database",
        "search_for_card": "Search for card",
        "normal_monsters": "Normal Monsters",
        "effect_monsters": "Effect Monsters",
        "pendulum_monsters": "Pendulum Monsters",
        "ritual_monsters": "Ritual Monsters",
        "fusion_monsters": "Fusion Monsters",
        "fusion_pendulum_monsters": "Pendulum Fusion Monsters",
        "synchro_monsters": "Synchro Monsters",
        "synchro_pendulum_monsters": "Pendulum Synchro Monsters",
        "xyz_monsters": "XYZ Monsters",
        "xyz_pendulum_monsters": "Pendulum XYZ Monsters",
        "link_monsters": "LINK Monsters",
        # ================================
        #  DUELISTS - DUEL MONSTERS
        # ================================
        "yugi_muto": "Yugi Muto",
        "seto_kaiba": "Seto Kaiba",
        "joey_wheeler": "Joey Wheeler",
        "tea_gardner": "Téa Gardner",
        "tristan_taylor": "Tristan Taylor",
        "solomon_muto": "Solomon Muto",
        "maximillion_pegasus": "Maximillion Pegasus",
        "lumis": "Lumis",
        "umbra": "Umbra",
        "dartz": "Dartz",
        "anubis": "Anubis",
        "duke_devlin": "Duke Devlin",
        "arkana": "Arkana",
        "weevil_underwood": "Weevil Underwood",
        "mai_valentine": "Mai Valentine",
        "mako_tsunami": "Mako Tsunami",
        "bonz": "Bonz",
        "alister": "Alister",
        "arthur_hopkins": "Arthur Hawkins",
        "rebecca": "Rebecca Hawkins",
        "ishizu_ishtar": "Ishizu Ishtar",
        "duel_computers": "Duel Computers",
        "ventriloquist_of_the_dead": "Ventriloquist of the Dead",
        "serenity_wheeler": "Serenity Wheeler",
        "panik": "PaniK",
        "mokuba_kaiba": "Mokuba Kaiba",
        "shimon_muran": "Shimon Muran",
        "yami_yugi": "Yami Yugi",
        "bakura_ryou": "Bakura Ryou",
        "yami_bakura": "Yami Bakura",
        "shadi": "Shadi",
        "rex_raptor": "Rex Raptor",
        "bandit_keith": "Bandit Keith",
        "para": "Para",
        "dox": "Dox",
        "marik_ishtar": "Marik Ishtar",
        "yami_marik": "Yami Marik",
        "odion": "Odion",
        "seeker": "Seeker",
        "strings": "Strings",
        "noah_kaiba": "Noah Kaiba",
        "gozaburo_kaiba": "Gozaburo Kaiba",
        "rafael": "Rafael",
        "valon": "Valon",
        "espa_roba": "Espa Roba",
        "big5": "The Big Five",
        "grand_championship_duelists": "KC Grand Prix",
        "other_duelists_duel_monsters": "Other (Duel Monsters)",
        "lumis_and_umbra": "Lumis and Umbra",
        "paradox_brothers": "Paradox Brothers",
        "nitemare": "DarkNite/Nitemare",
        # ================================
        #  DUEL SPIRITS
        # ================================
        "dark_magician_girl": "Dark Magician Girl",
        "kuriboh": "Kuriboh",
        "red_eyes_black_dragon": "Red-Eyes Black Dragon",
        "dancing_fairy": "Dancing Fairy",
        "goblin_elite_attack_force": "Goblin Elite Attack Force",
        "brron_mad_king_of_dark_world": "Brron, Mad King of Dark World",
        "chaos_sorcerer": "Chaos Sorcerer",
        "honest": "Honest",
        "maiden_of_the_aqua": "Maiden of the Aqua",
        "winged_kuriboh": "Winged Kuriboh",
        # ================================
        #  DUELISTS - GX
        # ================================
        "jean_louis_bonaparte": "Jean-Louis Bonaparte",
        "slade_princeton": "Slade Princeton",
        "jaden_yuki": "Jaden Yuki",
        "syrus_truesdale": "Syrus Truesdale",
        "alexis_rhodes": "Alexis Rhodes",
        "chazz_princeton": "Chazz Princeton",
        "bastion_misawa": "Bastion Misawa",
        "zane_truesdale": "Zane Truesdale",
        "vellian_crowler": "Vellian Crowler",
        "blair_flannigan": "Blair Flannigan",
        "lyman_banner": "Lyman Banner",
        "pharaoh": "Pharaoh",
        "sheppard": "Sheppard",
        "chumley_huffington": "Chumley Huffington",
        "aster_phoenix": "Aster Phoenix",
        "tyranno_hassleberry": "Tyranno Hassleberry",
        "jesse_anderson": "Jesse Anderson",
        "axel_brodie": "Axel Brodie",
        "jim_crocodile_cook": "Jim Crocodile Cook",
        "adrian_gecko": "Adrian Gecko",
        "kagemaru": "Kagemaru",
        "camula": "Camula",
        "tania": "Tania",
        "don_zaloog": "Don Zaloog",
        "titan": "Titan",
        "abidos_the_third": "Abidos the Third",
        "atticus_rhodes": "Atticus Rhodes",
        "sartorius_kumar": "Sartorius Kumar",
        "alien_of_light": "Alien of Light",
        "lorenzo": "Lorenzo",
        "howard_x_miller": "Howard X. Miller",
        "rose": "Rose",
        "sarina": "Sarina",
        "frost": "Frost",
        "thunder": "Thunder",
        "t_bone": "T-Bone",
        "prince_ojin": "Prince Ojin",
        "yubel": "Yubel",
        "thelonious_viper": "Thelonious Viper",
        "stein": "Stein",
        "trapper": "Trapper",
        "marcel_bonaparte": "Marcel Bonaparte",
        "anger_mask": "Anger Mask",
        "laughter_mask": "Laughter Mask",
        "emotionless_mask": "Emotionless Mask",
        "the_supreme_king": "The Supreme King",
        "skull_bishop": "Skull Bishop",
        "skilled_dark_magician": "Skilled Dark Magician",
        "scarr_scout_of_dark_world": "Scarr, Scout of Dark World",
        "zure_knight_of_dark_world": "Zure, Knight of Dark World",
        "kozaky": "Kozaky",
        "trueman": "Trueman",
        "yusuke_fujiwara": "Yusuke Fujiwara",
        "nightshroud": "Nightshroud",
        "fonda_fontaine": "Fonda Fontaine",
        "mindy": "Mindy",
        "jasmine": "Jasmine",
        "sartyr": "Sartyr",
        "sadie": "Sadie",
        "taiyou_torimaki": "Taiyou Torimaki",
        "raizou_mototani": "Raizou Mototani",
        "torrey": "Torrey",
        "harrington_rosewood": "Harrington Rosewood",
        "brier": "Brier",
        "beauregard": "Beauregard",
        "dimitri": "Dimitri",
        "america_uchimura": "America Uchimura",
        "ishiki_erishi": "Ishiki Erishi",
        "belowski": "Belowski",
        "reginald_van_howel": "Reginald Van Howel",
        "missy": "Missy",
        "ojama_trio": "Ojama Trio",
        "neo_spacians": "Neo-Spacians",
        "neo_spacian_air_hummingbird": "Neo-Spacian Air Hummingbird",
        "neo_spacian_grand_mole": "Neo-Spacian Grand Mole",
        "des_frog": "Des Frog",
        "neo_spacian_dark_panther": "Neo-Spacian Dark Panther",
        "the_winged_dragon_of_ra": "The Winged Dragon of Ra",
        "destiny_hero_plasma": "Destiny HERO - Plasma",
        "elemental_hero_neos": "Elemental HERO Neos",
        "crystal_beast_sapphire_pegasus": "Crystal Beast Sapphire Pegasus",
        "jerry_beans_man": "Jerry Beans Man",
        "rainbow_dragon": "Rainbow Dragon",
        "elemental_hero_flame_wingman": "Elemental HERO Flame Wingman",
        "sky_scout": "Sky Scout",
        "exodia_the_forbidden_one": "Exodia the Forbidden One",
        "kabukid": "Kabukid",
        "franz": "Franz",
        "mathmatica": "Mathmatica",
        "mr_huffington": "Mr. Huffington",
        "jagger_princeton": "Jagger Princeton",
        "the_admiral": "The Admiral",
        "pierre_the_gambler": "Pierre the Gambler",
        "eisenstein": "Eisenstein",
        "lucien_grimley": "Lucien Grimley",
        "shido_gecko": "Shido Gecko",
        "tom": "Tom",
        "osamu": "Osamu",
        "makoto_inotsume": "Makoto Inotsume",
        "daigo_sorano": "Daigo Sorano",
},
    "pt": {
        #================================
        #   LOADING FRAME
        #================================
        "loading_title": "Inicializando aplicação ",
        "loading_cards": "Carregando cartas...",
        "loading_tip": "Aguarde alguns instantes...",
        "loading_error": "Erro ao carregar banco de dados!",
        "loading_translations": "Carregando traduções...",
        # ===============================
        #   CHANGING LANGUAGE DIALOG
        # ===============================
        "changing_language_title": "Mudando idioma",
        "changing_language": "Mudando idioma, por favor aguarde",
        "error": "Erro",
        "language_change_failed": "Erro ao trocar idioma!",
        # ================================
        #   HEADER
        # ================================
        "read_docs": "Arquivo de Consistência de Cartas",
        "language": "Idioma",
        # ================================
        #   HOME FRAME
        # ================================
        "home_title": "Bem-vindo(a) ao Companion App de Yu-Gi-Oh! para Desktop",
        "home_subtitle": "Consulte cartas, visualize decks de duelistas e monte seus próprios decks.",
        "check_cards": "Ver cartas disponíveis",
        "duelists": "Ver duelistas",
        "custom_decks": "Ver decks personalizados",
        "cards_total": "Total de cartas",
        "duelists_total": "Total de duelistas",
        "user_decks_total": "Total de decks de usuário",
        "dataset_version": "Versão do dataset",
        "dataset_version_unknown": "Versão do dataset: desconhecida",
        "last_update": "Atualizado em",
        "show_new_cards": "Exibir cartas novas",
        "no_new_cards_added": "Nenhuma carta nova adicionada",
        "no_new_cards": "Não há cartas novas para exibir",
        # ================================
        #  CARDS FRAME
        # ================================
        "search_card": "Buscar cartas",
        # ================================
        #  DUELISTS FRAME
        # ================================
        "select_duelist": "Selecionar duelista",
        "filter_all": "Todos duelistas",
        "duel_monsters_anime": "Monstros de Duelo",
        "duel_spirits": "Espíritos de Duelo",
        "gx": "GX",
        "filter_by": "Filtrar por",
        "search_duelist": "Procurar duelista",
        "search_duel_spirit": "Procurar Espírito de Duelo",
        "select_duel_spirit": "Selecionar Espírito de Duelo",
        # ================================
        #  DUELISTS DETAILS FRAME
        # ================================
        "complete_deck": "Deck completo",
        "incomplete_deck": "Deck incompleto",
        "duelist_decks": "Decks de {name}",
        "show_exclusive_cards": "Mostrar cartas exclusivas",
        "no_decks_found": "Nenhum deck encontrado",
        "export_deck": "Exportar deck(s)",
        "deck_exporter": "Exportador de deck",
        "deck_export_success": "Deck exportado com sucesso!",
        "decks_export_success": "Decks exportados com sucesso!",
        "deck_export_fail": "Erro! falha ao exportar Deck",
        "deck_import_success": "Deck importado com sucesso!",
        "decks_import_success": "Decks importados com sucesso!",
        "no_decks_exported": "Nenhum deck foi exportado",
        "generate_deck": "Gerar deck",
        "not_enough_cards": "Não há cartas suficientes para gerar um deck",
        "deck_generator": "Gerador de deck",
        "generated_deck": "Deck derado",
        "generate_another_deck": "Gerar outro deck",
        "text_view": "Texto",
        "gallery_view": "Galeria",
        "loading": "Carregando...",
        "deck": "Deck",
        "export_individual_deck": "Exportar deck",
        # ================================
        #  CUSTOM DECKS AND CUSTOM DECK EDITOR FRAME
        # ================================
        "import_deck": "Importar deck(s)",
        "deck_importer": "Importador de Deck",
        "could_not_read_deck_file": "Erro ao ler arquivo de deck!",
        "invalid_card_entry": "Erro! Formato de carta incorreto",
        "could_not_import_card": "Erro ao importar carta",
        "deck_imported_successfully": "Deck importado com sucesso!",
        "deck_import_failed": "Erro ao importar deck",
        "deck_name": "Nome do deck",
        "total_cards": "Deck Principal / Extra",
        "used": "Utilizado",
        "new_deck": "Criar novo deck",
        "edit": "Editar deck",
        "toggle_used": "Marcar/Desmarcar usado",
        "delete": "Excluir deck",
        "add_to_deck": "Adicionar ao deck",
        "remove_one": "Remover uma cópia",
        "remove_card": "Remover cartas",
        "yes": "Sim",
        "no": "Não",
        "editing_deck": "Agora editando",
        "deck_cards": "Cartas do deck",
        "enter_deck_name": "Insira nome do deck",
        "enter_imported_deck_name": "Insira nome do deck importado",
        "delete_deck": "Excluir deck(s)",
        "deck_remover": "Removedor de deck",
        "deck_deleted_successfully": "Deck(s) excluído(s) com sucesso!",
        "no_decks_deleted": "Nenhum deck para excluir",
        "confirm_delete_deck": "Tem certeza que deseja excluir este deck?",
        "confirm_delete_decks": "Tem certeza que deseja excluir estes decks?",
        "deck_name_already_exists": "Já existe um deck com esse nome.",
        "rename_deck": "Renomear deck",
        "no_decks_to_export": "Selecione um deck para exportar",
        "deck_not_found": "Deck não encontrado",
        "search_decks": "Procurar decks",
        "invalid_deck_file": "Arquivo de deck inválido",
        "limit_reached": "Limite alcançado",
        "card_limit_reached": "Não é possível adicionar mais cartas. Limite de 3 alcançado.",
        "deck_notes": "Observações do deck",
        "unsaved_changes": "Confirmar alterações",
        "save_before_closing": "Houve alterações no arquivo. Deseja salvar?",
        "confirm_operation": "Confirmar operação",
        "confirm_mark_deck_as_used": 'Deseja marcar o deck "{deck_name}" como usado?',
        "confirm_mark_deck_as_unused": 'Deseja marcar o deck "{deck_name}" como não usado?',
        # ================================
        #  UI
        # ================================
        "return": "Voltar",
        "select_card": "Escolha uma carta",
        "card_details": "Mostrar detalhes da carta",
        "spell_card": "Carta Mágica",
        "trap_card": "Carta Armadilha",
        "skill_card": "Carta de Habilidade",
        "main_deck": "Deck Principal",
        "extra_deck": "Deck Extra",
        "monsters": "Cartas Monstro",
        "spells": "Cartas Mágicas",
        "traps": "Cartas Armadilhas",
        "exclusive_cards": "Cartas Exclusivas",
        "other_cards": "Outras cartas",
        "new_cards_added": "Novas cartas adicionadas",
        "click_for_more_details": "Clique em uma carta para conferir mais detalhes",
        "cards_added": "Carta(s) adicionada(s)",
        "update_available_title": "Nova atualização disponivel!",
        "update_available_message": "Há uma nova atualização. Deseja instalar?",
        "no_changelog_available": "Nenhum registro de mudanças foi encontrado",
        "download_update": "Baixar atualização",
        "downloading_update": "Baixando atualização",
        "ignore": "Ignorar",
        "open_in_browser": "Abrir no navegador",
        "download_complete": "Download concluído!",
        "update_downloaded": "Atualização baixada! Aguarde alguns instantes até que o programa reinicie",
        "update_fail": "Erro ao baixar atualização!",
        "updater_not_found": "Erro! Atualizador não encontrado!",
        "cards": "cartas",
        "loading_database": "Carregando banco de dados",
        "search_for_card": "Procurar carta",
        "normal_monsters": "Monstros Normais",
        "effect_monsters": "Monstros de Efeito",
        "pendulum_monsters": "Monstros Pêndulo",
        "ritual_monsters": "Monstros Ritual",
        "fusion_monsters": "Monstros Fusão",
        "fusion_pendulum_monsters": "Monstros Fusão Pêndulo",
        "synchro_monsters": "Monstros Sincro",
        "synchro_pendulum_monsters": "Monstros Sincro Pêndulo",
        "xyz_monsters": "Monstros XYZ",
        "xyz_pendulum_monsters": "Monstros XYZ Pêndulo",
        "link_monsters": "Monstros LINK",
        # ================================
        #  DUELISTS - DUEL MONSTERS
        # ================================
        "yugi_muto": "Yugi Muto",
        "seto_kaiba": "Seto Kaiba",
        "joey_wheeler": "Joey Wheeler",
        "tea_gardner": "Téa Gardner",
        "tristan_taylor": "Tristan Taylor",
        "solomon_muto": "Solomon Muto",
        "maximillion_pegasus": "Maximillion Pegasus",
        "lumis": "Lumis",
        "umbra": "Umbra",
        "dartz": "Dartz",
        "anubis": "Anúbis",
        "duke_devlin": "Duke Devlin",
        "arkana": "Arkana",
        "weevil_underwood": "Weevil Underwood",
        "mai_valentine": "Mai Valentine",
        "mako_tsunami": "Mako Tsunami",
        "bonz": "Bonz",
        "alister": "Alister",
        "arthur_hopkins": "Arthur Hawkins",
        "rebecca": "Rebecca Hawkins",
        "ishizu_ishtar": "Ishizu Ishtar",
        "duel_computers": "Computadores de Duelo",
        "ventriloquist_of_the_dead": "Ventriloquista dos Mortos",
        "serenity_wheeler": "Serenity Wheeler",
        "panik": "PaniK",
        "mokuba_kaiba": "Mokuba Kaiba",
        "shimon_muran": "Shimon Muran",
        "yami_yugi": "Yami Yugi",
        "bakura_ryou": "Bakura Ryou",
        "yami_bakura": "Yami Bakura",
        "shadi": "Shadi",
        "rex_raptor": "Rex Raptor",
        "bandit_keith": "Bandit Keith",
        "para": "Para",
        "dox": "Dox",
        "marik_ishtar": "Marik Ishtar",
        "yami_marik": "Yami Marik",
        "odion": "Odion",
        "seeker": "Seeker",
        "strings": "Strings",
        "noah_kaiba": "Noah Kaiba",
        "gozaburo_kaiba": "Gozaburo Kaiba",
        "rafael": "Rafael",
        "valon": "Valon",
        "espa_roba": "Espa Roba",
        "big5": "Os Cinco Grandes",
        "grand_championship_duelists": "Grand Prix KC",
        "other_duelists_duel_monsters": "Outros (Monstros de Duelo)",
        "lumis_and_umbra": "Lumis e Umbra",
        "paradox_brothers": "Irmãos Paradox",
        "nitemare": "DarkNite/Nitemare",
        # ================================
        #  DUEL SPIRITS
        # ================================
        "dark_magician_girl": "Pequena Maga Negra",
        "kuriboh": "Kuriboh",
        "red_eyes_black_dragon": "Dragão Negro de Olhos Vermelhos",
        "dancing_fairy": "Fada Dançante",
        "goblin_elite_attack_force": "Força de Ataque de Elite Goblin",
        "brron_mad_king_of_dark_world": "Brron, Rei Insano do Mundo Negro",
        "chaos_sorcerer": "Feiticeiro do Caos",
        "honest": "Honesto",
        "maiden_of_the_aqua": "Donzela da Água",
        "winged_kuriboh": "Kuriboh Alado",
        # ================================
        #  DUELISTS - GX
        # ================================
        "jean_louis_bonaparte": "Jean-Louis Bonaparte",
        "slade_princeton": "Slade Princeton",
        "jaden_yuki": "Jaden Yuki",
        "syrus_truesdale": "Syrus Truesdale",
        "alexis_rhodes": "Alexis Rhodes",
        "chazz_princeton": "Chazz Princeton",
        "bastion_misawa": "Bastion Misawa",
        "zane_truesdale": "Zane Truesdale",
        "vellian_crowler": "Vellian Crowler",
        "blair_flannigan": "Blair Flannigan",
        "lyman_banner": "Lyman Banner",
        "pharaoh": "Pharaoh",
        "sheppard": "Sheppard",
        "chumley_huffington": "Chumley Huffington",
        "aster_phoenix": "Aster Phoenix",
        "tyranno_hassleberry": "Tyranno Hassleberry",
        "jesse_anderson": "Jesse Anderson",
        "axel_brodie": "Axel Brodie",
        "jim_crocodile_cook": "Jim Crocodile Cook",
        "adrian_gecko": "Adrian Gecko",
        "kagemaru": "Kagemaru",
        "camula": "Camula",
        "tania": "Tania",
        "don_zaloog": "Don Zaloog",
        "titan": "Titan",
        "abidos_the_third": "Abidos the Third",
        "atticus_rhodes": "Atticus Rhodes",
        "sartorius_kumar": "Sartorius Kumar",
        "alien_of_light": "Alien of Light",
        "lorenzo": "Lorenzo",
        "howard_x_miller": "Howard X. Miller",
        "rose": "Rose",
        "sarina": "Sarina",
        "frost": "Frost",
        "thunder": "Thunder",
        "t_bone": "T-Bone",
        "prince_ojin": "Prince Ojin",
        "yubel": "Yubel",
        "thelonious_viper": "Thelonious Viper",
        "stein": "Stein",
        "trapper": "Trapper",
        "marcel_bonaparte": "Marcel Bonaparte",
        "anger_mask": "Anger Mask",
        "laughter_mask": "Laughter Mask",
        "emotionless_mask": "Emotionless Mask",
        "the_supreme_king": "The Supreme King",
        "skull_bishop": "Skull Bishop",
        "skilled_dark_magician": "Skilled Dark Magician",
        "scarr_scout_of_dark_world": "Scarr, Scout of Dark World",
        "zure_knight_of_dark_world": "Zure, Knight of Dark World",
        "kozaky": "Kozaky",
        "trueman": "Trueman",
        "yusuke_fujiwara": "Yusuke Fujiwara",
        "nightshroud": "Nightshroud",
        "fonda_fontaine": "Fonda Fontaine",
        "mindy": "Mindy",
        "jasmine": "Jasmine",
        "sartyr": "Sartyr",
        "sadie": "Sadie",
        "taiyou_torimaki": "Taiyou Torimaki",
        "raizou_mototani": "Raizou Mototani",
        "torrey": "Torrey",
        "harrington_rosewood": "Harrington Rosewood",
        "brier": "Brier",
        "beauregard": "Beauregard",
        "dimitri": "Dimitri",
        "america_uchimura": "America Uchimura",
        "ishiki_erishi": "Ishiki Erishi",
        "belowski": "Belowski",
        "reginald_van_howel": "Reginald Van Howel",
        "missy": "Missy",
        "ojama_trio": "Ojama Trio",
        "neo_spacians": "Neo-Spacians",
        "neo_spacian_air_hummingbird": "Neo-Spacian Air Hummingbird",
        "neo_spacian_grand_mole": "Neo-Spacian Grand Mole",
        "des_frog": "Des Frog",
        "neo_spacian_dark_panther": "Neo-Spacian Dark Panther",
        "the_winged_dragon_of_ra": "The Winged Dragon of Ra",
        "destiny_hero_plasma": "Destiny HERO - Plasma",
        "elemental_hero_neos": "Elemental HERO Neos",
        "crystal_beast_sapphire_pegasus": "Crystal Beast Sapphire Pegasus",
        "jerry_beans_man": "Jerry Beans Man",
        "rainbow_dragon": "Rainbow Dragon",
        "elemental_hero_flame_wingman": "Elemental HERO Flame Wingman",
        "sky_scout": "Sky Scout",
        "exodia_the_forbidden_one": "Exodia the Forbidden One",
        "kabukid": "Kabukid",
        "franz": "Franz",
        "mathmatica": "Mathmatica",
        "mr_huffington": "Mr. Huffington",
        "jagger_princeton": "Jagger Princeton",
        "the_admiral": "O Almirante",
        "pierre_the_gambler": "Pierre, o Apostador",
        "eisenstein": "Eisenstein",
        "lucien_grimley": "Lucien Grimley",
        "shido_gecko": "Shido Gecko",
        "tom": "Tom",
        "osamu": "Osamu",
        "makoto_inotsume": "Makoto Inotsume",
        "daigo_sorano": "Daigo Sorano",
        # ================================
        #  CARDS DETAILS TRANSLATIONS
        # ================================
        # type + subtype
        "Spell Card": "Carta Mágica",
        "Effect": "Efeito",
        "Trap Card": "Carta Armadilha",
        "Normal": "Normal",
        "Pendulum Effect": "Pêndulo Efeito",
        "Fusion": "Fusão",
        "Flip Effect": "Efeito Virar",
        "Ritual Effect": "Efeito Ritual",
        "Tuner": "Regulador",
        "Link": "Link",
        "Token": "Ficha",
        "Normal Tuner": "Regulador Normal",
        "Synchro Tuner": "Regulador Synchro",
        "Spirit": "Espírito",
        "Pendulum Tuner Effect": "Pêndulo Regulador Efeito",
        "Union Effect": "União",
        "XYZ Pendulum Effect": "XYZ Pêndulo Efeito",
        "Gemini": "Gêmeo",
        "Pendulum Effect Fusion": "Pêndulo Fusão Efeito",
        "Pendulum Normal": "Pêndulo Normal",
        "Pendulum Effect Ritual": "Pêndulo Efeito Ritual",
        "Flip Tuner Effect": "Regulador Efeito Virar",
        "Pendulum Flip Effect": "Pêndulo Efeito Virar",
        "Synchro Pendulum Effect": "Synchro Pêndulo Efeito",
        "Skill Card": "Carta de Habilidade",
        # race
        "Quick-Play": "Jogada Rápida",
        "Fiend": "Demônio",
        "Dragon": "Dragão",
        "Continuous": "Contínua",
        "Zombie": "Zumbi",
        "Beast-Warrior": "Besta Guerreira",
        "Fairy": "Fada",
        "Warrior": "Guerreiro",
        "Rock": "Rocha",
        "Spellcaster": "Mago",
        "Winged Beast": "Besta Alada",
        "Plant": "Planta",
        "Beast": "Besta",
        "Machine": "Máquina",
        "Equip": "Equipamento",
        "Field": "Campo",
        "Fish": "Peixe",
        "Thunder": "Trovão",
        "Pyro": "Fogo",
        "Sea Serpent": "Serpente Marítima",
        "Aqua": "Água",
        "Reptile": "Réptil",
        "Counter": "Contra-Ataque",
        "Psychic": "Psíquico",
        "Insect": "Inseto",
        "Illusion": "Ilusão",
        "Dinosaur": "Dinossauro",
        "Divine-Beast": "Besta Divina",
        "Creator God": "Deus Criador",
        # atrributes
        "DARK": "TREVAS",
        "LIGHT": "LUZ",
        "EARTH": "TERRA",
        "FIRE": "FOGO",
        "WIND": "VENTO",
        "WATER": "ÁGUA",
        "DIVINE": "DIVINO",
    }
}
